### ISSUE TITLE
Are there any documentation or guidelines for external developers

### ISSUE THREAD

**Issue by SYaoJun** [dingodb/dingo-store#350]

**Comment by astor-oss** [comment]
Thank you for your interest in our project. We acknowledge that the current documentation might not be comprehensive enough, but we're continuously working to improve it. `Dingo-Store` is a distributed key-value storage engine based on Raft, providing SDK capabilities - you may refer to the examples in the Java section. It also offers an SQL execution engine corresponding to the [Dingo](https://github/dingodb/dingo) project. For the design details of Dingo-Store, please refer to the linked resources [Design of Dingo-Store](https://dingodb.readthedocs.io/en/latest/architecture/design/store.html)].

**Comment by SYaoJun** [comment]
OK
